import type { NextPage } from 'next';
import Head from 'next/head';
import { Main } from '@layout';
import { Form } from 'react-bootstrap';

type ICompletetion = {};

const Loja: NextPage = () => {
  const {
    handleSubmit,
    register,
    reset,
    formState: { errors },
  } = useForm<ICompletetion>();

  const onSubmit: SubmitHandler<ICompletetion> = async (
    data: ICompletetion,
  ) => {};

  return (
    <>
      <Head>
        <title>Loja</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main>
        <h1>prencha os dados adicionais</h1>
        <section>
          <Form className="col-12" onSubmit={handleSubmit(onSubmit)}>
            <Form.Group className=" mb-3" controlId="exampleForm.ControlInput1">
              <Form.Label>Nome:</Form.Label>
              <Form.Control
                type="name"
                {...register('name', {
                  required: true,
                  minLength: 3,
                  maxLength: 20,
                  pattern: /^[a-z ,.'-]+$/i,
                })}
                placeholder={'Digite seu nome'}
                style={{
                  border: `${
                    errors.name ? '2px solid #f51717' : '1px solid #ccc'
                  }`,
                }}
              />

              <Form.Label>Email:</Form.Label>
              <Form.Control
                type="email"
                {...register('email', {
                  required: true,
                  minLength: 3,
                  pattern: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                })}
                placeholder="Digite seu email"
                style={{
                  border: `${
                    errors.email ? '2px solid #f51717' : '1px solid #ccc'
                  }`,
                }}
              />
              <Form.Label>Proposta:</Form.Label>
              <Form.Control
                rows={3}
                as="textarea"
                {...register('message', {
                  required: true,
                  maxLength: 200,
                })}
                placeholder="Me envie uma mensagem"
                style={{
                  border: `${
                    errors.message ? '2px solid #f51717' : '1px solid #ccc'
                  }`,
                }}
              />
              <div className="enviar col-auto ">
                <button>Enviar mensagem</button>
              </div>
            </Form.Group>
          </Form>
        </section>
      </Main>
    </>
  );
};

export default Loja;
