import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { Main } from '@layout';
import Head from 'next/head';
import { ApprovedPaymentScreen, RejectedPaymentScreen } from '@components';

type QueryParams = {
  payment_id: string;
  status: string;
  payment_type: string;
  merchant_order_id: string;
  collection_id: string;
  collection_status: string;
  external_reference: string | null;
  preference_id: string;
  processing_mode: string;
  merchant_account_id: string | null;
  site_id: string;
};

const Feedback = () => {
  const router = useRouter();
  const [queryParams, setQueryParams] = useState<QueryParams | null>(null);

  useEffect(() => {
    const searchParams = new URLSearchParams(router.asPath.split('?')[1]);
    const params: QueryParams = {
      payment_id: searchParams.get('payment_id') || '',
      status: searchParams.get('status') || '',
      payment_type: searchParams.get('payment_type') || '',
      merchant_order_id: searchParams.get('merchant_order_id') || '',
      collection_id: searchParams.get('collection_id') || '',
      collection_status: searchParams.get('collection_status') || '',
      external_reference: searchParams.get('merchant_order_id') || '',
      preference_id: searchParams.get('preference_id') || '',
      processing_mode: searchParams.get('processing_mode') || '',
      merchant_account_id: searchParams.get('merchant_account_id') || '',
      site_id: searchParams.get('site_id') || '',
    };
    setQueryParams(params);
  }, [router.asPath]);

  let content;

  switch (queryParams?.status) {
    case 'approved':
      content = <ApprovedPaymentScreen />;
      break;
    case 'rejected':
      content = <RejectedPaymentScreen />;
      break;
    default:
      content = <p>status não definido</p>;
      break;
  }

  return (
    <>
      <Head>
        <title>Feedback de Pagamento</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Main>
        <section>{content}</section>
      </Main>
    </>
  );
};

export default Feedback;

/* {queryParams && (
  <>
           <p>Payment: {queryParams.payment_id}</p>
    <p>Status: {queryParams.status}</p>
    <p>Payment Type: {queryParams.payment_type}</p>
    <p>Merchant Order: {queryParams.merchant_order_id}</p>
    <p>Collection ID: {queryParams.collection_id}</p>
    <p>Collection Status: {queryParams.collection_status}</p>
    <p>External Reference: {queryParams.external_reference}</p>
    <p>Preference ID: {queryParams.preference_id}</p>
    <p>Processing Mode: {queryParams.processing_mode}</p>
    <p>Merchant Account ID: {queryParams.merchant_account_id}</p>
    <p>Site ID: {queryParams.site_id}</p>
  </>
)} */
