import React from 'react';
import Head from 'next/head';
import { Col, Container, Row } from 'react-bootstrap';
import { useRouter } from 'next/router';

import type { NextPage } from 'next';

import { ProductData } from '@interfaces';
import { CartView, ProducInfo, ProductView } from '@components';
import Layout from '@layout';
import { Section } from '@styles/pages/loja/product';

const Producto: NextPage = () => {
  const router = useRouter();

  const { produto } = router.query;

  const [produtos, setProdutos] = React.useState<ProductData[]>([]);

  React.useEffect(() => {
    if (typeof produto == 'string') {
      const parsedProduct = JSON.parse(produto);
      setProdutos([parsedProduct]);
    }
  }, [produto]);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout bgColor="white" txColor="black" staticmenu title="Produto">
        <Container>
          <Section>
            {/*  barra superior  */}
            <Row className="bar">
              <Col className="voltar">
                <button onClick={() => router.push('/loja')}>Voltar</button>
              </Col>
              <CartView />
            </Row>

            <Row className="my-4 justify-content-around">
              {produtos &&
                produtos.map((produto, index) => (
                  <>
                    <Col
                      className="product-imgens d-flex"
                      xs={12}
                      lg={5}
                      md={6}
                    >
                      <ProductView key={index} {...{ produto }} />
                    </Col>

                    <Col
                      className="prodoct-infos d-flex flex-column"
                      xs={12}
                      lg={5}
                      md={6}
                    >
                      <ProducInfo key={index} {...{ produto }} />
                    </Col>
                  </>
                ))}
            </Row>

            {!produtos.length && <p>produto não encontrado</p>}
          </Section>
        </Container>
      </Layout>
    </>
  );
};

export default Producto;
