import React from 'react';
import Head from 'next/head';
import { Col, Container, Row } from 'react-bootstrap';
import { useRouter } from 'next/router';

import type { NextPage } from 'next';

import { ProductData } from '@interfaces';
import { CartView, DataNotLoaded, ProducInfo, ProductView } from '@components';
import Layout from '@layout';
import { Section } from '@styles/pages/loja/product';

const Producto: NextPage = () => {
  const router = useRouter();

  const { produto } = router.query;

  const [produtos, setProdutos] = React.useState<ProductData[]>([]);

  React.useEffect(() => {
    if (typeof produto == 'string') {
      const parsedProduct = JSON.parse(produto);
      setProdutos([parsedProduct]);
    }
  }, [produto]);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout bgColor="white" txColor="black" staticmenu title="Produto">
        <Container>
          <Section>
            <Row className="bar">
              <Col className="voltar">
                <button onClick={() => router.push('/loja')}>Voltar</button>
              </Col>
              <CartView />
            </Row>

            {produtos.length === 1 && (
              <Row className="my-4 justify-content-around">
                <Col className="product-imgens" xs={12} lg={5} md={6}>
                  <ProductView {...{ produto: produtos[0] }} />
                </Col>
                <Col className="prodoct-infos" xs={12} lg={5} md={6}>
                  <ProducInfo {...{ produto: produtos[0] }} />
                </Col>
              </Row>
            )}

            {!produtos.length && <DataNotLoaded />}
          </Section>
        </Container>
      </Layout>
    </>
  );
};

export default Producto;
