import type { NextPage } from 'next';
import Head from 'next/head';
import { Main } from '@layout';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Main>
        <section style={{ backgroundColor: 'white', textAlign: 'center' }}>
          <h1>
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word
          </h1>
          <h1>
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word hello word hello word hello word
            hello word hello word hello word
          </h1>
        </section>
      </Main>
    </>
  );
};

export default Home;
