import type { NextPage } from 'next';
import Head from 'next/head';

const Loja: NextPage = () => {
    return (
        <>
            <Head>
                <title>Loja</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <section>
                <h1>hello word 2</h1>
            </section>
        </>
    );
};

export default Loja;
